// Change this single value to relocate the entire admin panel to a new secret path.
export const ADMIN_BASE = '/nexrnn/master-nexrnn/admin';

export const ADMIN_ROUTES = {
  login: `${ADMIN_BASE}/login`,
  dashboard: ADMIN_BASE,
  leadsContact: `${ADMIN_BASE}/leads/contact`,
  leadsServices: `${ADMIN_BASE}/leads/services`,
  leadsCourses: `${ADMIN_BASE}/leads/courses`,
  leadsWorkshops: `${ADMIN_BASE}/leads/workshops`,
  payments: `${ADMIN_BASE}/payments`,
  analytics: `${ADMIN_BASE}/analytics`,
  courseParticipantsPath: `${ADMIN_BASE}/courses/:batchId/enrollment`,
  workshopParticipantsPath: `${ADMIN_BASE}/workshops/:batchId/enrollment`,
  courseParticipants: (batchId) => `${ADMIN_BASE}/courses/${batchId}/enrollment`,
  workshopParticipants: (batchId) => `${ADMIN_BASE}/workshops/${batchId}/enrollment`,
  siteSettings: `${ADMIN_BASE}/settings`,
  services: `${ADMIN_BASE}/services`,
  serviceNew: `${ADMIN_BASE}/services/new`,
  serviceEdit: (id) => `${ADMIN_BASE}/services/${id}/edit`,
  serviceEditPath: `${ADMIN_BASE}/services/:id/edit`,
  courses: `${ADMIN_BASE}/courses`,
  courseNew: `${ADMIN_BASE}/courses/new`,
  courseEdit: (id) => `${ADMIN_BASE}/courses/${id}/edit`,
  courseEditPath: `${ADMIN_BASE}/courses/:id/edit`,
  blogPosts: `${ADMIN_BASE}/blog`,
  blogPostNew: `${ADMIN_BASE}/blog/new`,
  blogPostEdit: (id) => `${ADMIN_BASE}/blog/${id}/edit`,
  blogPostEditPath: `${ADMIN_BASE}/blog/:id/edit`,
  caseStudies: `${ADMIN_BASE}/case-studies`,
  caseStudyNew: `${ADMIN_BASE}/case-studies/new`,
  caseStudyEdit: (id) => `${ADMIN_BASE}/case-studies/${id}/edit`,
  caseStudyEditPath: `${ADMIN_BASE}/case-studies/:id/edit`,
  careers: `${ADMIN_BASE}/careers`,
  careerNew: `${ADMIN_BASE}/careers/new`,
  careerEdit: (id) => `${ADMIN_BASE}/careers/${id}/edit`,
  careerEditPath: `${ADMIN_BASE}/careers/:id/edit`,
  internshipApplications: `${ADMIN_BASE}/internship-applications`,
  mentors: `${ADMIN_BASE}/mentors`,
  mentorIssues: `${ADMIN_BASE}/mentor-issues`,
  mentorPayments: `${ADMIN_BASE}/mentor-payments`,
  promoCodes: `${ADMIN_BASE}/promo-codes`,
  clientReviews: `${ADMIN_BASE}/client-reviews`,
  clientReviewNew: `${ADMIN_BASE}/client-reviews/new`,
  clientReviewEdit: (id) => `${ADMIN_BASE}/client-reviews/${id}/edit`,
  clientReviewEditPath: `${ADMIN_BASE}/client-reviews/:id/edit`,
  portfolio: `${ADMIN_BASE}/portfolio`,
  portfolioNew: `${ADMIN_BASE}/portfolio/new`,
  portfolioEdit: (id) => `${ADMIN_BASE}/portfolio/${id}/edit`,
  portfolioEditPath: `${ADMIN_BASE}/portfolio/:id/edit`,
  testimonials: `${ADMIN_BASE}/testimonials`,
  testimonialNew: `${ADMIN_BASE}/testimonials/new`,
  testimonialEdit: (id) => `${ADMIN_BASE}/testimonials/${id}/edit`,
  testimonialEditPath: `${ADMIN_BASE}/testimonials/:id/edit`,
  workshops: `${ADMIN_BASE}/workshops`,
  workshopNew: `${ADMIN_BASE}/workshops/new`,
  workshopEdit: (id) => `${ADMIN_BASE}/workshops/${id}/edit`,
  workshopEditPath: `${ADMIN_BASE}/workshops/:id/edit`,
};
